In [3]:
from sklearn.datasets import load_boston
boston = load_boston()

In [4]:
print(boston.keys())

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [5]:
print(boston.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]

In [6]:
import pandas as pd

data = pd.DataFrame(boston.data)
data.columns = boston.feature_names
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [7]:
data['PRICE'] = boston.target

In [8]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [9]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

In [10]:
X, y = data.iloc[:,:-1],data.iloc[:,-1]

In [12]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: PRICE, Length: 506, dtype: float64

In [13]:
#data_dmatrix = xgb.DMatrix(data=X,label=y)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [19]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

#Â Fit part
This is the fist part

In [20]:
xg_reg.fit(X_train,y_train)

[17:18:55] WARNING: /tmp/build/80754af9/xgboost-split_1619724447847/work/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.3, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=5,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=10, n_jobs=3, num_parallel_tree=1,
             objective='reg:linear', random_state=0, reg_alpha=10, reg_lambda=1,
             scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [21]:
preds = xg_reg.predict(X_test)

In [22]:
preds

array([ 9.103588 , 16.20727  , 21.957262 , 11.070463 , 21.300505 ,
       12.276793 , 18.925522 ,  7.083111 , 11.746751 , 20.013893 ,
       19.179705 , 14.53166  , 10.709933 , 15.127511 , 13.538791 ,
       13.893654 , 13.701075 , 22.320995 , 13.731371 , 11.8415365,
       10.999017 ,  9.195716 , 20.330471 , 21.024662 , 18.657934 ,
       14.092796 , 10.383664 , 14.616508 , 15.38663  , 11.616503 ,
       14.560661 , 19.2781   ,  7.1106486, 14.901539 , 15.12312  ,
       21.536554 , 15.02078  ,  9.512263 , 12.906651 , 22.195372 ,
       17.663647 , 13.731371 ,  8.118485 , 18.258696 , 12.396344 ,
       18.608946 , 14.056596 , 15.12312  , 13.168913 , 11.10647  ,
       19.2781   , 16.806429 , 13.673577 ,  8.748699 , 13.654837 ,
       10.659364 , 12.159043 ,  7.7301702, 20.330471 ,  8.748699 ,
       12.416452 , 13.254661 ,  8.918394 , 11.220913 , 13.893654 ,
       16.20727  , 15.771129 , 11.358969 , 14.743051 , 18.596249 ,
       13.331196 , 15.887696 , 13.168913 , 16.190044 , 10.659364 ,
       10.5787735,  8.434358 , 14.495949 , 17.395761 ,  7.04747  ,
       20.239305 ,  9.489446 , 15.247116 , 13.731371 , 13.1016245,
       15.401251 , 10.119193 , 17.307741 , 13.701075 , 19.619713 ,
        8.767946 , 20.001196 , 13.109932 , 15.700208 , 21.713484 ,
       16.204273 , 12.116433 , 20.790422 , 14.607339 , 24.235079 ,
       14.901539 , 10.218023 ], dtype=float32)

In [27]:
y_test

410    15.0
85     26.6
280    45.4
422    20.8
199    34.9
       ...
229    31.5
159    23.3
196    33.3
345    17.5
467    19.1
Name: PRICE, Length: 102, dtype: float64

In [24]:
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))

RMSE: 10.915755

In [25]:
params = {"objective":"reg:linear",'colsample_bytree': 0.3,'learning_rate': 0.1,
                'max_depth': 5, 'alpha': 10}

cv_results = xgb.cv(dtrain=data_dmatrix, params=params, nfold=3,
                    num_boost_round=50,early_stopping_rounds=10,metrics="rmse", as_pandas=True, seed=123)

[17:20:54] WARNING: /tmp/build/80754af9/xgboost-split_1619724447847/work/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[17:20:54] WARNING: /tmp/build/80754af9/xgboost-split_1619724447847/work/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[17:20:54] WARNING: /tmp/build/80754af9/xgboost-split_1619724447847/work/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.

In [26]:
cv_results.head()

   train-rmse-mean  train-rmse-std  test-rmse-mean  test-rmse-std
0        21.654681        0.033232       21.671270       0.060740
1        19.749899        0.043431       19.775093       0.030386
2        18.041173        0.035790       18.141612       0.038490
3        16.439292        0.071154       16.558766       0.049052
4        15.062128        0.102330       15.247309       0.089738